pipeline {
    agent any
    stages {
        
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('build && SonarQube analysis') {
            steps {
            	script {
            		withSonarQubeEnv('sonar') {
	                	sh 'mvn sonar:sonar'
	                }
            	}
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }
        
        stage('Copy to documents') {
            steps {
                bat 'copy %WORKSPACE%\\target\\*.jar C:\\Users\\collabera\\Documents'
            }
        }
    }
    post {
	    always {
	      bat 'copy %JENKINS_HOME%\\jobs\\%JOB_NAME%\\builds\\%BUILD_NUMBER%\\log C:\\Users\\collabera\\Documents\\log.txt'
	    }
	}
}