pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Copy to documents') {
            steps {
                bat 'copy %WORKSPACE%\\target\\*.jar C:\\Users\\collabera\\Documents'
            }
        }
        stage('Save logs') {
            steps {
                bat 'copy %WORKSPACE%\\target\\*.jar C:\\Users\\collabera\\Documents'
            }
        }
    }
    post {
	    always {
	      bat 'curl -o C:\\Users\\collabera\\Documents\\jenkins-build-log.txt %BUILD_URL%/consoleText'
	    }
	}
}